### ISSUE TITLE
Criar tela de carrinho

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-frontend#25]
## Description
Uma funcionalidade básica de qualquer ecommerce é ter um carrinho onde o cliente possa visualizar e alterar os itens que ele deseja comprar, e aqui não é diferente.  
Nesse contexto deve ser criada uma tela que requisita para a rota `/users/{user_id}/cart` e obtém as informações de carrinho do usuário. 
Caso não haja nenhum carrinho ativo, ou ele esteja vazio, deve-se exibir uma mensagem dizendo que "Não há nada no carrinho".  
Caso contrário, deve-se listar os Pokémons que o usuário deseja comprar, mostrando seu nome, foto e quantidade. Deve-se também permitir removê-los do carrinho via um botão e alterar sua quantidade escolhida.  
Ao clicar no item pode-se abrir uma visualização mais detalhada.

## Additional context
- **A exclusão de itens do carrinho ainda não está pronta, assim como a alteração da quantidade, então só deixar preparado os gatilhos.**
- **Não esqueça de mostrar o total da compra em algum lugar.**
![image](https://github.com/afmireski/garchop-frontend/assets/54330175/04ed8500-1ddf-4683-86cf-7dd9016b4f71)

## Tasks

- [ ] Obter dados da API.
- [ ] Listar itens do carrinho.
	- [ ] Preparar mensagem de carrinho vazio
- [ ] Montar botão de excluir item do carrinho.
- [x] ~Implementar switch de troca de quantidade.~
- [ ] Redirecionar para detalhes do Pokémon quando clicar no item.
- [ ] Atualizar `CHANGELOG.md`
