### ISSUE TITLE
Alterar telas de CRUD de Pokémon

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-frontend#27]
## Tasks

- [ ] Modificar a interface do usuário para listar os nomes dos usuários existentes ao editar/excluir um pokemon.
- [ ]  Implementar a lógica para carregar os nomes dos pokemon existentes na interface de edição/exclusão.
- [ ]  Adicionar um campo oculto para enviar o ID do pokemon junto com a requisição de edição/exclusão.
- [ ]  Atualizar a documentação do código para refletir as mudanças feitas.
- [ ]  Testar as operações de edição/exclusão para garantir que funcionem corretamente.
- [ ] Atualizar `CHANGELOG.md`
