### ISSUE TITLE
Autenticar chamadas para rotas

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-frontend#31]
## Description
A maioria das rotas da aplicação estarão protegidas por autenticação, tornando necessário passar o `token` obtido no login como um parâmetro chamado `Authorization` nos `headers` de certas requisições.

### Exemplo de código
```typescript
import axios from 'axios';

const token = 'your_authorization_token';

axios.get('/api/endpoint', {
  headers: {
    Authorization: `${token}`,
  },
})
  .then(response => {
    // Handle the response
  })
  .catch(error => {
    // Handle the error
  });
```

## Tasks

- [ ] Autenticar as seguintes chamadas de rotas:
	- [ ] `/users/{id}/update`
	- [ ] `/users/{id}`
	- [ ] `/users/admin`
	- [ ] `/users/{id}/del`
	- [ ] `/admin/new`
	- [ ] `/tiers`
	- [ ] `/tiers/{id}`
	- [ ] `/pokemon/new`
	- [ ] `/pokemon/{id}/update`
	- [ ] `/pokemon/{id}/del`
	- [ ] `/carts/{cart_id}/items/{item_id}`
	- [ ] `/users/{user_id}/cart`
	- [ ] `/users/{user_id}/items/add`
	- [ ] `/purchases/finish`
- [ ] Implementar logout
	- [ ] Fazer requisição para a rota: `/sign-out`
- [ ] Atualizar `CHANGELOG.md`
