### ISSUE TITLE
Implementar botão de finalizar compra

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-frontend#33]
## Description
Como principal função do ecommerce, deve-se permitir que o usuário finalize sua compra.
Para finalizar a compra deve-se fazer uma requisição para a rota: `/purchases/finish`, passando o token de autenticação no `Authorization` Header.

Para quesitos de feedback, o botão de finalizar compra deve ficar desabilitado caso a quantidade de itens no carrinho seja zero.

É interessante que também seja dado algum feedback para o usuário dizendo se a operação foi um sucesso ou não. Isso pode ser feito via Popup, ou Toast Message.

### Body da requisição
```json
{
	"user_id": "uuid",
	"cart_id": "uuid",
	"payment_method_id": "8c75baa8-ac41-4bff-a8a0-89c777ecde27" // Deixe fixo por enquanto
}
```

## Tasks

- [ ] Implementar chamada para a API.
- [ ] Bloquear clique no botão.
- [ ] Implementar feedback com Toast.
- [ ] Atualizar `CHANGELOG.md`
