### ISSUE TITLE
Implementar pesquisa básica na tela de listagem de pokémons

### ISSUE THREAD

**Issue by afmireski** [afmireski/garchop-frontend#35]
## Description
Clientes de um ecommerce devem poder filtrar os pokemons que eles desejam comprar via uma busca simples.

Isso pode ser feito adicionando um campo de pesquisa na tela de listagem que requisita a mesma rota de listagem, `/pokemon`, porém adicionando o seguinte parâmetro de query: `filter`

### Exemplo de requisição
- **Requisite inicialmente com a API na branch afmireski/garchop-api#61**
- **/pokemon?filter=param**
- **Valor do filtro:**
```json
{
	"name": {
		"like": "%<valor pesquisado>%"
	}
}
```

### Extra
- **Aproveitar para corrigir um problema de usabilidade, tornar os cards de Pokémon clicáveis por completo**

## Tasks

- [x] Implementar campo de pesquisa
- [ ] Implementar chamada para a API
- [x] Tornar cards de pokémon clicáveis.
- [x] Atualizar `CHANGELOG.md`
