### ISSUE TITLE
Implementar tela de detalhes de um item da compra

### ISSUE THREAD

**Issue by atenokida** [afmireski/garchop-frontend#37]
## Description
Uma compra é composta por um ou mais itens. A issue [#34](https://github.com/afmireski/garchop-frontend/issues/34) descreve a implementação de uma tela para a listagem de todas as compras de um usuário. Entretanto, para uma melhor experiência do usuário, seria interessante uma tela que exiba detalhes de um item da compra.

Sugestão: Criar a tela na rota `/profile/orders/details/{item_id}`.

## Additional context
--

## Tasks
- [ ] Implementar tela de detalhes de um item da compra
- [ ] Validações:
	- [ ] Exibir informação de inválido caso o id da compra seja inválido.
	- [ ] Exibir informação de inexistente caso a compra seja inexistente.
	- [ ] Somente o usuário associado à compra pode ter acesso aos detalhes do item.
- [ ] Atualizar `CHANGELOG.md`
