### ISSUE TITLE
Implementar a tela de pokedex, e sua tela de detalhes correspondente

### ISSUE THREAD

**Issue by gustavoreino** [afmireski/garchop-frontend#45]
## Description
Crie uma tela para apresentar os pokemons do usuário e tela de detalhes para acompanhar.

## Additional context
Use como referência a tela de home, tirando os detalhes de compra.

## Tasks
- [x] Integrar a requisição da API
- [x] Criar a tela de pokedex
- [x] Criar a tela de detalhes

**Comment by gustavoreino** [comment]
Todas as funcionalidades foram implementadas.
